Verifica arquivos protegidos do repositório antes de salvar a avaliação
betrybe/store-evaluation-action pull request #31
Opened 2022-08-15 22:00 UTC by renanvy

2022-08-16 12:26 UTC, AdrielBento approved these changes

2022-08-16 12:50 UTC, johnnytaira approved these changes
LGTM

2022-08-16 14:34 UTC, josecfreittas requested changes
Encontrei a seguinte falha:
O `BASE_COMMIT` é o commit para onde o PR está apontando, e ele não necessariamente é a branch main/master.

Exemplificando:
* Criei [esse PR 1](https://github.com/betrybe/sd-00-staging-individual-2022-08-16-11-02-40/pull/2) modificando o evaluation-data no workflow, adicionando meu grade como 3 em todos os requisitos.
* O `PR 1` falhou, pois o store-evaluation comparou os arquivos protegidos com o `BASE_COMMIT`, que é a `main` aqui.
* Criei o [PR 2](https://github.com/betrybe/sd-00-staging-individual-2022-08-16-11-02-40/pull/3) a partir do `PR 1`, e apontando para o `PR 1`.
* Comparando com a branch `main`, o `PR 2` contém a modificação maliciosa do workflow e uma modificação no README, mas comparando com o `PR 1`, somente o README foi modificado. 
* Como o `PR 2` aponta para o `PR 1`, o `BASE_COMMIT` do `PR 2` é o `PR 1`, não a `main`.
* Como não tiverem modificações de arquivos protegidos comparando o o `PR 2` com o `PR 1`, o avaliador aceita, executando o workflow malicioso, me dando nota máxima.

2022-08-17 17:23 UTC, renanvy commented
> Encontrei a seguinte falha:
> O `BASE_COMMIT` é o commit para onde o PR está apontando, e ele não necessariamente é a branch main/master.

@josecfreittas vlw demais por ter levantado isso. Fiz um ajuste pra resolver isso, pode conferir por favor?

2022-08-17 17:45 UTC, josecfreittas approved these changes

2022-08-17 17:47 UTC, merged